import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/navbar";
import { Hero } from "../components/hero";
import { Description } from "../components/description";
import { Product } from "../components/product";
import { Contactinfo } from "../components/contact info";
import { Footer } from "../components/footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <Navbar />
        <Hero />
        <Description />
        <Product />
        <Contactinfo />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
