import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div className="bg-black w-64 rounded">
              <p className="text-white">The quick brown fox...</p>
          </div>


      </main>

 </div>
  )
}

export default Home
